apiVersion: apps/v1
kind: Deployment
metadata:
  name: fork-knife-backend
  namespace: fork-knife-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fork-knife-backend
  template:
    metadata:
      labels:
        app: fork-knife-backend
    spec:
      containers:
      - name: backend
        image: your-registry/fork-knife-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: fork-knife-secrets
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: fork-knife-secrets
              key: jwt-secret
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: fork-knife-secrets
              key: stripe-secret
        - name: REDIS_HOST
          value: "redis-service"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: fork-knife-backend-service
  namespace: fork-knife-production
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: fork-knife-backend

